apiVersion: v2
name: mesh-controller
description: Mesh Controller for Decentralized Control Plane
type: application
version: "0.0.0"
appVersion: "0.0.0"
home: https://github.com/HIRO-MicroDataCenters-BV/mesh-controller
maintainers:
  - name: HIRO-Microdatacenters
    url: https://hiro-microdatacenters.nl
