[workspace]
resolver = "2"
members = [
  "mesh"
]

[workspace.lints.rust]

[workspace.dependencies]
anyhow = "1.0.93"
axum = "0.7.9"
axum-prometheus = "0.7.0"
async-nats = "0.37.0"
async-trait = "0.1.83"
bytes = "1.8.0"
ciborium = "0.2.2"
hex = "0.4.3"
clap = { version = "4.5.8", features = ["derive"] }
p2panda-core = { git = "https://github.com/p2panda/p2panda.git", tag="v0.2.0" }
p2panda-net = { git = "https://github.com/p2panda/p2panda.git", default-features = false, tag="v0.2.0" }
p2panda-sync = { git = "https://github.com/p2panda/p2panda.git", features = ["cbor"], default-features = false, tag="v0.2.0" }
p2panda-discovery = { git = "https://github.com/p2panda/p2panda.git", tag="v0.2.0" }
mesh = { path = "mesh" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9"
futures-lite = "2.5.0"
futures-util = "0.3.31"
thiserror = "2.0.12"
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
url = "2.5.3"
directories = "5.0.1"
figment = { version = "0.10.19", features = ["env", "yaml"] }
rand = "0.8.5"
loole = "0.4.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tempfile = "3.10.1"
rusty-hook = "^0.11.2"
once_cell = "1.20.2"
dashmap = "6.1.0"
futures = { version = "0.3.28", default-features = false, features = ["std"] }
pin-project = "1.1.8"
hyper-util = { version = "0.1.10", features = [
    "server",
    "http1",
    "http2",
    "tokio",
] }
schemars = { version = "0.8.12", features = ["chrono"] }
built = { version = "0.7", features = ["chrono", "git2"] }
strum = { version = "0.26", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
pin-project-lite = { version = "0.2.4" }
# pinned version of rusttls due to iroh-net and stackable-operator/kube-rs
rustls = { version = "0.23" }
chrono = { version = "0.4.19" }
# TODO remove
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "stackable-operator-0.83.0" }
product-config = { git = "https://github.com/stackabletech/product-config.git", tag = "0.7.0" }
